"""
train_classifier.py — Train XGBoost distraction classifier.

Loads training data generated by generate_training_data.py,
trains an XGBClassifier, evaluates accuracy, and saves the model.

Why XGBoost?
  - Fast inference (~5ms per batch) — suitable for real-time classification
  - Handles tabular data well without normalization
  - Provides predict_proba() for confidence scores
  - No GPU required — runs on CPU in the Docker container

Run: python scripts/train_classifier.py
Requires: python scripts/generate_training_data.py to be run first
Output: backend/models/distraction_clf.joblib
        backend/models/feature_cols.joblib
"""
import pandas as pd
import numpy as np
import joblib
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from xgboost import XGBClassifier

# These must match exactly what generate_training_data.py outputs
# AND what analytics.py sends to the model at inference time.
# Saving them to feature_cols.joblib prevents mismatches.
FEATURE_COLS = [
    'avg_focus_60s',
    'focus_std_60s',
    'blink_rate',
    'head_pose_deg',
    'time_of_day_norm',
    'session_duration_sec',
    'subject_id_encoded',
]

CAUSE_LABELS = {
    0: 'fatigue',
    1: 'difficulty',
    2: 'environment',
    3: 'unknown',
}

if __name__ == "__main__":
    # ── Load data ─────────────────────────────────────────────────────────────
    data_path = Path(__file__).parent / "training_data.csv"
    if not data_path.exists():
        print("ERROR: training_data.csv not found.")
        print("Run: python scripts/generate_training_data.py first")
        exit(1)

    df = pd.read_csv(data_path)
    print(f"Loaded {len(df)} samples")

    X = df[FEATURE_COLS]
    y = df['label']

    # ── Train/test split ──────────────────────────────────────────────────────
    # stratify=y ensures each class gets the same proportion in train and test.
    # Without this, a random split might put all 'unknown' samples in one set.
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"Train: {len(X_train)} samples | Test: {len(X_test)} samples")

    # ── Train XGBoost ─────────────────────────────────────────────────────────
    # n_estimators=100: build 100 trees (more = better accuracy, slower training)
    # max_depth=6: each tree can split up to 6 times (controls overfitting)
    # learning_rate=0.1: how much each tree corrects the previous errors
    # eval_metric='mlogloss': multi-class log loss (standard for classification)
    model = XGBClassifier(
        n_estimators=100,
        max_depth=6,
        learning_rate=0.1,
        random_state=42,
        eval_metric='mlogloss',
        verbosity=0,  # silence XGBoost's own output
    )
    model.fit(X_train, y_train)

    # ── Evaluate ──────────────────────────────────────────────────────────────
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\nAccuracy: {accuracy:.2%}")
    print("\nClassification report:")
    print(classification_report(
        y_test, y_pred,
        target_names=[CAUSE_LABELS[i] for i in range(4)]
    ))

    if accuracy < 0.75:
        print("WARNING: accuracy below 75% — check training data distributions")
    else:
        print(f"Model quality OK: {accuracy:.2%}")

    # ── Save model ────────────────────────────────────────────────────────────
    # The models/ directory is mounted into the Docker container via volumes,
    # so once saved here it is immediately available to the running API.
    models_dir = Path(__file__).parent.parent / "models"
    models_dir.mkdir(exist_ok=True)

    model_path = models_dir / "distraction_clf.joblib"
    joblib.dump(model, model_path)
    print(f"\nModel saved to: {model_path}")

    # Save feature column order — analytics.py loads this to guarantee
    # features are fed to the model in the exact same order as training.
    cols_path = models_dir / "feature_cols.joblib"
    joblib.dump(FEATURE_COLS, cols_path)
    print(f"Feature columns saved to: {cols_path}")
